model = "gpt-5.3-codex"
model_reasoning_effort = "high"

web_search = "live"
personality = "pragmatic"

[projects."/Users/danielchen/projects/ytlm"]
trust_level = "trusted"

[projects."/Users/danielchen/code/homebot"]
trust_level = "trusted"

[projects."/Users/danielchen"]
trust_level = "trusted"

[projects."/Users/danielchen/code/PupPilot"]
trust_level = "trusted"

[projects."/Users/danielchen/projects/ai-research-comparison"]
trust_level = "trusted"

[projects."/Users/danielchen/projects/ai-agent-comparison"]
trust_level = "untrusted"

[projects."/Users/danielchen/projects/ai-agent-comparison/web-search-2026-1-27"]
trust_level = "trusted"

[projects."/Users/danielchen/code"]
trust_level = "untrusted"

[projects."/Users/danielchen/code/openclaw"]
trust_level = "trusted"

[projects."/Users/danielchen/code/homebot/quasar"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
